### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by leshack** [Tut-k0/htb-academy-to-md#1]
The error I get when running the exe using the correct format  
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
main.getModulePages({0xc000248a00, 0x144b}, {0xc0000103c0, 0x36})
        /home/tut/Programming/go/htb-academy-md/src/export.go:204 +0x177
main.getModule({0xc0000103c0, 0x36}, {{0xc000264090?, 0x8?}, {0xc000170000?, 0x3bd668?}})
        /home/tut/Programming/go/htb-academy-md/src/export.go:133 +0x3b4
main.main()
        /home/tut/Programming/go/htb-academy-md/src/main.go:13 +0xd7

**Comment by Tut-k0** [comment]
Hi there,

Thank you for reaching out and providing the error message. This error usually occurs when a module that is not unlocked is attempted to be downloaded. With the non-existent error handing (something that I should add 😅), this could be due to several factors.

To assist further, can you please provide me some additional information:

1. **Module Identification**: Can you please specify which module you are attempting to convert when you encounter this error? Knowing the specific module will help narrow down the issue.

2. **Module Unlock Status**: Additionally, could you confirm whether you have unlocked/bought the mentioned module? The application does not have a check for this currently, and will fail with a similar error to the one your provided if the module is not unlocked.

3. **Authentication Method**: Are you using regular email and password-based authentication, or have you set up 2FA (Two-Factor Authentication) as well? This information could help determine if the issue might be related to authentication. The application was not tested with 2FA and would most likely cause a fail if enabled on the user account.

**Comment by leshack** [comment]
I have a 2FA set that could be the problem. The modules are unlocked and
tried different modules to confirm the issue

**Comment by Tut-k0** [comment]
With 2FA being enabled, I will go ahead and mark this issue as a to-do for a future feature. I can't promise a timeline for implementing 2FA support as I currently have a few other projects ongoing that are taking up a lot of my time. 

In the meantime if you wanted to use the tool you could disable 2FA for the program to run and add it back after. I also am open to accepting pull requests, so if this is something you were interested in adding to the tool sooner than later, feel free to give it a shot!

**Comment by Tut-k0** [comment]
Hi @TectonicKestrel , do you have this issue with just this specific module or all modules? Also, could you let me know which cookies are you passing with the `-c` argument? In my local testing, only the `htb_academy_session` is really needed to be included for me to be able to fetch down a module.

I have not been able to replicate the issue locally on the newest release located [here](https://github.com/Tut-k0/htb-academy-to-md/releases/tag/v1.1.3), unless I omitted passing valid cookies. I was not testing against your specific module though, as I do not own it.

**Comment by Tut-k0** [comment]
Closing this issue out as the original 2FA concerns should now be resolved with the program using session cookies rather than the login workflow.
